// File generated by FlutterFire CLI (modificado para incluir Web).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // ✅ Soporte para Web
    if (kIsWeb) {
      return web;
    }

    // ✅ Soporte para plataformas móviles
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      // Puedes agregar más plataformas si las configuras después
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no está configurado para esta plataforma.',
        );
    }
  }

  // 🔹 CONFIGURACIÓN WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOwlAjDm7Z91V4ZBdn0h58_dF2UpYySWs',
    appId: '1:439920887949:web:3788de207ad6f8a4c03ac4',
    messagingSenderId: '439920887949',
    projectId: 'eccmanager-fffdd',
    authDomain: 'eccmanager-fffdd.firebaseapp.com',
    storageBucket: 'eccmanager-fffdd.firebasestorage.app',
    measurementId: 'G-VZ0YBG75VL',
  );

  // 🔹 CONFIGURACIÓN ANDROID
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWx3-WornVNlNAmcLBAeteG9lhxWzT_g',
    appId: '1:439920887949:android:2b97da61cc990edbc03ac4',
    messagingSenderId: '439920887949',
    projectId: 'eccmanager-fffdd',
    storageBucket: 'eccmanager-fffdd.firebasestorage.app',
  );

  // 🔹 CONFIGURACIÓN IOS (opcional, ya la tenías)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL7bwLiPCBbyMkDZ_bvX3sC9fQ1EAjJOo',
    appId: '1:439920887949:ios:72b2139c6b791b6fc03ac4',
    messagingSenderId: '439920887949',
    projectId: 'eccmanager-fffdd',
    storageBucket: 'eccmanager-fffdd.firebasestorage.app',
    iosBundleId: 'com.example.eccmanager',
  );
}